const eplData = {
    "2023-2024赛季": {
        "matches":[
            { round: 1, home: "伯恩利", away: "曼城", homeScore: 0, awayScore: 3 },
            { round: 1, home: "阿森纳", away: "诺丁汉森林", homeScore: 2, awayScore: 1 },
            { round: 1, home: "伯恩茅斯", away: "West Ham", homeScore: 1, awayScore: 1 },
            { round: 1, home: "埃弗顿", away: "富勒姆", homeScore: 0, awayScore: 1 },
            { round: 1, home: "Brighton", away: "Luton", homeScore: 4, awayScore: 1 },
            { round: 1, home: "Sheffield Utd", away: "水晶宫", homeScore: 0, awayScore: 1 },
            { round: 1, home: "Newcastle", away: "阿斯顿维拉", homeScore: 5, awayScore: 1 },
            { round: 1, home: "布伦特福德", away: "Tottenham", homeScore: 2, awayScore: 2 },
            { round: 1, home: "切尔西", away: "利物浦", homeScore: 1, awayScore: 1 },
            { round: 1, home: "曼联", away: "Wolves", homeScore: 1, awayScore: 0 },
            { round: 2, home: "诺丁汉森林", away: "Sheffield Utd", homeScore: 2, awayScore: 1 },
            { round: 2, home: "富勒姆", away: "布伦特福德", homeScore: 0, awayScore: 3 },
            { round: 2, home: "Wolves", away: "Brighton", homeScore: 1, awayScore: 4 },
            { round: 2, home: "利物浦", away: "伯恩茅斯", homeScore: 3, awayScore: 1 },
            { round: 2, home: "Tottenham", away: "曼联", homeScore: 2, awayScore: 0 },
            { round: 2, home: "曼城", away: "Newcastle", homeScore: 1, awayScore: 0 },
            { round: 2, home: "阿斯顿维拉", away: "埃弗顿", homeScore: 4, awayScore: 0 },
            { round: 2, home: "West Ham", away: "切尔西", homeScore: 3, awayScore: 1 },
            { round: 2, home: "水晶宫", away: "阿森纳", homeScore: 0, awayScore: 1 },
            { round: 3, home: "切尔西", away: "Luton", homeScore: 3, awayScore: 0 },
            { round: 3, home: "伯恩茅斯", away: "Tottenham", homeScore: 0, awayScore: 2 },
            { round: 3, home: "曼联", away: "诺丁汉森林", homeScore: 3, awayScore: 2 },
            { round: 3, home: "阿森纳", away: "富勒姆", homeScore: 2, awayScore: 2 },
            { round: 3, home: "埃弗顿", away: "Wolves", homeScore: 0, awayScore: 1 },
            { round: 3, home: "布伦特福德", away: "水晶宫", homeScore: 1, awayScore: 1 },
            { round: 3, home: "Brighton", away: "West Ham", homeScore: 1, awayScore: 3 },
            { round: 3, home: "伯恩利", away: "阿斯顿维拉", homeScore: 1, awayScore: 3 },
            { round: 3, home: "Sheffield Utd", away: "曼城", homeScore: 1, awayScore: 2 },
            { round: 3, home: "Newcastle", away: "利物浦", homeScore: 1, awayScore: 2 },
            { round: 4, home: "Luton", away: "West Ham", homeScore: 1, awayScore: 2 },
            { round: 4, home: "Sheffield Utd", away: "埃弗顿", homeScore: 2, awayScore: 2 },
            { round: 4, home: "伯恩利", away: "Tottenham", homeScore: 2, awayScore: 5 },
            { round: 4, home: "切尔西", away: "诺丁汉森林", homeScore: 0, awayScore: 1 },
            { round: 4, home: "曼城", away: "富勒姆", homeScore: 5, awayScore: 1 },
            { round: 4, home: "布伦特福德", away: "伯恩茅斯", homeScore: 2, awayScore: 2 },
            { round: 4, home: "Brighton", away: "Newcastle", homeScore: 3, awayScore: 1 },
            { round: 4, home: "利物浦", away: "阿斯顿维拉", homeScore: 3, awayScore: 0 },
            { round: 4, home: "水晶宫", away: "Wolves", homeScore: 3, awayScore: 2 },
            { round: 4, home: "阿森纳", away: "曼联", homeScore: 3, awayScore: 1 },
            { round: 5, home: "Wolves", away: "利物浦", homeScore: 1, awayScore: 3 },
            { round: 5, home: "曼联", away: "Brighton", homeScore: 1, awayScore: 3 },
            { round: 5, home: "富勒姆", away: "Luton", homeScore: 1, awayScore: 0 },
            { round: 5, home: "Tottenham", away: "Sheffield Utd", homeScore: 2, awayScore: 1 },
            { round: 5, home: "West Ham", away: "曼城", homeScore: 1, awayScore: 3 },
            { round: 5, home: "阿斯顿维拉", away: "水晶宫", homeScore: 3, awayScore: 1 },
            { round: 5, home: "Newcastle", away: "布伦特福德", homeScore: 1, awayScore: 0 },
            { round: 5, home: "伯恩茅斯", away: "切尔西", homeScore: 0, awayScore: 0 },
            { round: 5, home: "埃弗顿", away: "阿森纳", homeScore: 0, awayScore: 1 },
            { round: 5, home: "诺丁汉森林", away: "伯恩利", homeScore: 1, awayScore: 1 },
            { round: 6, home: "曼城", away: "诺丁汉森林", homeScore: 2, awayScore: 0 },
            { round: 6, home: "水晶宫", away: "富勒姆", homeScore: 0, awayScore: 0 },
            { round: 6, home: "Luton", away: "Wolves", homeScore: 1, awayScore: 1 },
            { round: 6, home: "布伦特福德", away: "埃弗顿", homeScore: 1, awayScore: 3 },
            { round: 6, home: "伯恩利", away: "曼联", homeScore: 0, awayScore: 1 },
            { round: 6, home: "利物浦", away: "West Ham", homeScore: 3, awayScore: 1 },
            { round: 6, home: "阿森纳", away: "Tottenham", homeScore: 2, awayScore: 2 },
            { round: 6, home: "切尔西", away: "阿斯顿维拉", homeScore: 0, awayScore: 1 },
            { round: 6, home: "Brighton", away: "伯恩茅斯", homeScore: 3, awayScore: 1 },
            { round: 6, home: "Sheffield Utd", away: "Newcastle", homeScore: 0, awayScore: 8 },
            { round: 7, home: "阿斯顿维拉", away: "Brighton", homeScore: 6, awayScore: 1 },
            { round: 7, home: "曼联", away: "水晶宫", homeScore: 0, awayScore: 1 },
            { round: 7, home: "Newcastle", away: "伯恩利", homeScore: 2, awayScore: 0 },
            { round: 7, home: "伯恩茅斯", away: "阿森纳", homeScore: 0, awayScore: 4 },
            { round: 7, home: "Wolves", away: "曼城", homeScore: 2, awayScore: 1 },
            { round: 7, home: "埃弗顿", away: "Luton", homeScore: 1, awayScore: 2 },
            { round: 7, home: "West Ham", away: "Sheffield Utd", homeScore: 2, awayScore: 0 },
            { round: 7, home: "Tottenham", away: "利物浦", homeScore: 2, awayScore: 1 },
            { round: 7, home: "诺丁汉森林", away: "布伦特福德", homeScore: 1, awayScore: 1 },
            { round: 7, home: "富勒姆", away: "切尔西", homeScore: 0, awayScore: 2 },
            { round: 2, home: "Luton", away: "伯恩利", homeScore: 1, awayScore: 2 },
            { round: 8, home: "Luton", away: "Tottenham", homeScore: 0, awayScore: 1 },
            { round: 8, home: "曼联", away: "布伦特福德", homeScore: 2, awayScore: 1 },
            { round: 8, home: "富勒姆", away: "Sheffield Utd", homeScore: 3, awayScore: 1 },
            { round: 8, home: "伯恩利", away: "切尔西", homeScore: 1, awayScore: 4 },
            { round: 8, home: "埃弗顿", away: "伯恩茅斯", homeScore: 3, awayScore: 0 },
            { round: 8, home: "水晶宫", away: "诺丁汉森林", homeScore: 0, awayScore: 0 },
            { round: 8, home: "Wolves", away: "阿斯顿维拉", homeScore: 1, awayScore: 1 },
            { round: 8, home: "West Ham", away: "Newcastle", homeScore: 2, awayScore: 2 },
            { round: 8, home: "Brighton", away: "利物浦", homeScore: 2, awayScore: 2 },
            { round: 8, home: "阿森纳", away: "曼城", homeScore: 1, awayScore: 0 },
            { round: 9, home: "利物浦", away: "埃弗顿", homeScore: 2, awayScore: 0 },
            { round: 9, home: "Newcastle", away: "水晶宫", homeScore: 4, awayScore: 0 },
            { round: 9, home: "伯恩茅斯", away: "Wolves", homeScore: 1, awayScore: 2 },
            { round: 9, home: "曼城", away: "Brighton", homeScore: 2, awayScore: 1 },
            { round: 9, home: "布伦特福德", away: "伯恩利", homeScore: 3, awayScore: 0 },
            { round: 9, home: "诺丁汉森林", away: "Luton", homeScore: 2, awayScore: 2 },
            { round: 9, home: "切尔西", away: "阿森纳", homeScore: 2, awayScore: 2 },
            { round: 9, home: "Sheffield Utd", away: "曼联", homeScore: 1, awayScore: 2 },
            { round: 9, home: "阿斯顿维拉", away: "West Ham", homeScore: 4, awayScore: 1 },
            { round: 9, home: "Tottenham", away: "富勒姆", homeScore: 2, awayScore: 0 },
            { round: 10, home: "水晶宫", away: "Tottenham", homeScore: 1, awayScore: 2 },
            { round: 10, home: "切尔西", away: "布伦特福德", homeScore: 0, awayScore: 2 },
            { round: 10, home: "伯恩茅斯", away: "伯恩利", homeScore: 2, awayScore: 1 },
            { round: 10, home: "阿森纳", away: "Sheffield Utd", homeScore: 5, awayScore: 0 },
            { round: 10, home: "Wolves", away: "Newcastle", homeScore: 2, awayScore: 2 },
            { round: 10, home: "West Ham", away: "埃弗顿", homeScore: 0, awayScore: 1 },
            { round: 10, home: "利物浦", away: "诺丁汉森林", homeScore: 3, awayScore: 0 },
            { round: 10, home: "Brighton", away: "富勒姆", homeScore: 1, awayScore: 1 },
            { round: 10, home: "阿斯顿维拉", away: "Luton", homeScore: 3, awayScore: 1 },
            { round: 10, home: "曼联", away: "曼城", homeScore: 0, awayScore: 3 },
            { round: 11, home: "富勒姆", away: "曼联", homeScore: 0, awayScore: 1 },
            { round: 11, home: "伯恩利", away: "水晶宫", homeScore: 0, awayScore: 2 },
            { round: 11, home: "埃弗顿", away: "Brighton", homeScore: 1, awayScore: 1 },
            { round: 11, home: "曼城", away: "伯恩茅斯", homeScore: 6, awayScore: 1 },
            { round: 11, home: "布伦特福德", away: "West Ham", homeScore: 3, awayScore: 2 },
            { round: 11, home: "Sheffield Utd", away: "Wolves", homeScore: 2, awayScore: 1 },
            { round: 11, home: "Newcastle", away: "阿森纳", homeScore: 1, awayScore: 0 },
            { round: 11, home: "诺丁汉森林", away: "阿斯顿维拉", homeScore: 2, awayScore: 0 },
            { round: 11, home: "Luton", away: "利物浦", homeScore: 1, awayScore: 1 },
            { round: 11, home: "Tottenham", away: "切尔西", homeScore: 1, awayScore: 4 },
            { round: 12, home: "Wolves", away: "Tottenham", homeScore: 2, awayScore: 1 },
            { round: 12, home: "曼联", away: "Luton", homeScore: 1, awayScore: 0 },
            { round: 12, home: "阿森纳", away: "伯恩利", homeScore: 3, awayScore: 1 },
            { round: 12, home: "水晶宫", away: "埃弗顿", homeScore: 2, awayScore: 3 },
            { round: 12, home: "伯恩茅斯", away: "Newcastle", homeScore: 2, awayScore: 0 },
            { round: 12, home: "利物浦", away: "布伦特福德", homeScore: 3, awayScore: 0 },
            { round: 12, home: "West Ham", away: "诺丁汉森林", homeScore: 3, awayScore: 2 },
            { round: 12, home: "Brighton", away: "Sheffield Utd", homeScore: 1, awayScore: 1 },
            { round: 12, home: "阿斯顿维拉", away: "富勒姆", homeScore: 3, awayScore: 1 },
            { round: 12, home: "切尔西", away: "曼城", homeScore: 4, awayScore: 4 },
            { round: 13, home: "曼城", away: "利物浦", homeScore: 1, awayScore: 1 },
            { round: 13, home: "Newcastle", away: "切尔西", homeScore: 4, awayScore: 1 },
            { round: 13, home: "伯恩利", away: "West Ham", homeScore: 1, awayScore: 2 },
            { round: 13, home: "Sheffield Utd", away: "伯恩茅斯", homeScore: 1, awayScore: 3 },
            { round: 13, home: "诺丁汉森林", away: "Brighton", homeScore: 2, awayScore: 3 },
            { round: 13, home: "Luton", away: "水晶宫", homeScore: 2, awayScore: 1 },
            { round: 13, home: "布伦特福德", away: "阿森纳", homeScore: 0, awayScore: 1 },
            { round: 13, home: "Tottenham", away: "阿斯顿维拉", homeScore: 1, awayScore: 2 },
            { round: 13, home: "埃弗顿", away: "曼联", homeScore: 0, awayScore: 3 },
            { round: 13, home: "富勒姆", away: "Wolves", homeScore: 3, awayScore: 2 },
            { round: 14, home: "阿森纳", away: "Wolves", homeScore: 2, awayScore: 1 },
            { round: 14, home: "伯恩利", away: "Sheffield Utd", homeScore: 5, awayScore: 0 },
            { round: 14, home: "布伦特福德", away: "Luton", homeScore: 3, awayScore: 1 },
            { round: 14, home: "诺丁汉森林", away: "埃弗顿", homeScore: 0, awayScore: 1 },
            { round: 14, home: "Newcastle", away: "曼联", homeScore: 1, awayScore: 0 },
            { round: 14, home: "伯恩茅斯", away: "阿斯顿维拉", homeScore: 2, awayScore: 2 },
            { round: 14, home: "利物浦", away: "富勒姆", homeScore: 4, awayScore: 3 },
            { round: 14, home: "West Ham", away: "水晶宫", homeScore: 1, awayScore: 1 },
            { round: 14, home: "切尔西", away: "Brighton", homeScore: 3, awayScore: 2 },
            { round: 14, home: "曼城", away: "Tottenham", homeScore: 3, awayScore: 3 },
            { round: 15, home: "Wolves", away: "伯恩利", homeScore: 1, awayScore: 0 },
            { round: 15, home: "Luton", away: "阿森纳", homeScore: 3, awayScore: 4 },
            { round: 15, home: "富勒姆", away: "诺丁汉森林", homeScore: 5, awayScore: 0 },
            { round: 15, home: "Brighton", away: "布伦特福德", homeScore: 2, awayScore: 1 },
            { round: 15, home: "水晶宫", away: "伯恩茅斯", homeScore: 0, awayScore: 2 },
            { round: 15, home: "Sheffield Utd", away: "利物浦", homeScore: 0, awayScore: 2 },
            { round: 15, home: "曼联", away: "切尔西", homeScore: 2, awayScore: 1 },
            { round: 15, home: "阿斯顿维拉", away: "曼城", homeScore: 1, awayScore: 0 },
            { round: 15, home: "埃弗顿", away: "Newcastle", homeScore: 3, awayScore: 0 },
            { round: 15, home: "Tottenham", away: "West Ham", homeScore: 1, awayScore: 2 },
            { round: 16, home: "水晶宫", away: "利物浦", homeScore: 1, awayScore: 2 },
            { round: 16, home: "曼联", away: "伯恩茅斯", homeScore: 0, awayScore: 3 },
            { round: 16, home: "Wolves", away: "诺丁汉森林", homeScore: 1, awayScore: 1 },
            { round: 16, home: "Brighton", away: "伯恩利", homeScore: 1, awayScore: 1 },
            { round: 16, home: "Sheffield Utd", away: "布伦特福德", homeScore: 1, awayScore: 0 },
            { round: 16, home: "阿斯顿维拉", away: "阿森纳", homeScore: 1, awayScore: 0 },
            { round: 16, home: "富勒姆", away: "West Ham", homeScore: 5, awayScore: 0 },
            { round: 16, home: "埃弗顿", away: "切尔西", homeScore: 2, awayScore: 0 },
            { round: 16, home: "Luton", away: "曼城", homeScore: 1, awayScore: 2 },
            { round: 16, home: "Tottenham", away: "Newcastle", homeScore: 4, awayScore: 1 },
            { round: 17, home: "诺丁汉森林", away: "Tottenham", homeScore: 0, awayScore: 2 },
            { round: 17, home: "Newcastle", away: "富勒姆", homeScore: 3, awayScore: 0 },
            { round: 17, home: "切尔西", away: "Sheffield Utd", homeScore: 2, awayScore: 0 },
            { round: 17, home: "曼城", away: "水晶宫", homeScore: 2, awayScore: 2 },
            { round: 17, home: "伯恩利", away: "埃弗顿", homeScore: 0, awayScore: 2 },
            { round: 17, home: "阿森纳", away: "Brighton", homeScore: 2, awayScore: 0 },
            { round: 17, home: "West Ham", away: "Wolves", homeScore: 3, awayScore: 0 },
            { round: 17, home: "布伦特福德", away: "阿斯顿维拉", homeScore: 1, awayScore: 2 },
            { round: 17, home: "利物浦", away: "曼联", homeScore: 0, awayScore: 0 },
            { round: 18, home: "水晶宫", away: "Brighton", homeScore: 1, awayScore: 1 },
            { round: 18, home: "阿斯顿维拉", away: "Sheffield Utd", homeScore: 1, awayScore: 1 },
            { round: 18, home: "West Ham", away: "曼联", homeScore: 2, awayScore: 0 },
            { round: 18, home: "富勒姆", away: "伯恩利", homeScore: 0, awayScore: 2 },
            { round: 18, home: "Tottenham", away: "埃弗顿", homeScore: 2, awayScore: 1 },
            { round: 18, home: "诺丁汉森林", away: "伯恩茅斯", homeScore: 2, awayScore: 3 },
            { round: 18, home: "Luton", away: "Newcastle", homeScore: 1, awayScore: 0 },
            { round: 18, home: "利物浦", away: "阿森纳", homeScore: 1, awayScore: 1 },
            { round: 18, home: "Wolves", away: "切尔西", homeScore: 2, awayScore: 1 },
            { round: 19, home: "Newcastle", away: "诺丁汉森林", homeScore: 1, awayScore: 3 },
            { round: 19, home: "伯恩茅斯", away: "富勒姆", homeScore: 3, awayScore: 0 },
            { round: 19, home: "Sheffield Utd", away: "Luton", homeScore: 2, awayScore: 3 },
            { round: 19, home: "伯恩利", away: "利物浦", homeScore: 0, awayScore: 2 },
            { round: 19, home: "曼联", away: "阿斯顿维拉", homeScore: 3, awayScore: 2 },
            { round: 19, home: "切尔西", away: "水晶宫", homeScore: 2, awayScore: 1 },
            { round: 19, home: "布伦特福德", away: "Wolves", homeScore: 1, awayScore: 4 },
            { round: 19, home: "埃弗顿", away: "曼城", homeScore: 1, awayScore: 3 },
            { round: 19, home: "Brighton", away: "Tottenham", homeScore: 4, awayScore: 2 },
            { round: 19, home: "阿森纳", away: "West Ham", homeScore: 0, awayScore: 2 },
            { round: 20, home: "Luton", away: "切尔西", homeScore: 2, awayScore: 3 },
            { round: 20, home: "Wolves", away: "埃弗顿", homeScore: 3, awayScore: 0 },
            { round: 20, home: "曼城", away: "Sheffield Utd", homeScore: 2, awayScore: 0 },
            { round: 20, home: "水晶宫", away: "布伦特福德", homeScore: 3, awayScore: 1 },
            { round: 20, home: "阿斯顿维拉", away: "伯恩利", homeScore: 3, awayScore: 2 },
            { round: 20, home: "诺丁汉森林", away: "曼联", homeScore: 2, awayScore: 1 },
            { round: 20, home: "富勒姆", away: "阿森纳", homeScore: 2, awayScore: 1 },
            { round: 20, home: "Tottenham", away: "伯恩茅斯", homeScore: 3, awayScore: 1 },
            { round: 20, home: "利物浦", away: "Newcastle", homeScore: 4, awayScore: 2 },
            { round: 20, home: "West Ham", away: "Brighton", homeScore: 0, awayScore: 0 },
            { round: 21, home: "伯恩利", away: "Luton", homeScore: 1, awayScore: 1 },
            { round: 21, home: "切尔西", away: "富勒姆", homeScore: 1, awayScore: 0 },
            { round: 21, home: "Newcastle", away: "曼城", homeScore: 2, awayScore: 3 },
            { round: 21, home: "埃弗顿", away: "阿斯顿维拉", homeScore: 0, awayScore: 0 },
            { round: 21, home: "曼联", away: "Tottenham", homeScore: 2, awayScore: 2 },
            { round: 21, home: "阿森纳", away: "水晶宫", homeScore: 5, awayScore: 0 },
            { round: 21, home: "布伦特福德", away: "诺丁汉森林", homeScore: 3, awayScore: 2 },
            { round: 21, home: "Sheffield Utd", away: "West Ham", homeScore: 2, awayScore: 2 },
            { round: 21, home: "伯恩茅斯", away: "利物浦", homeScore: 0, awayScore: 4 },
            { round: 21, home: "Brighton", away: "Wolves", homeScore: 0, awayScore: 0 },
            { round: 22, home: "诺丁汉森林", away: "阿森纳", homeScore: 1, awayScore: 2 },
            { round: 22, home: "富勒姆", away: "埃弗顿", homeScore: 0, awayScore: 0 },
            { round: 22, home: "Luton", away: "Brighton", homeScore: 4, awayScore: 0 },
            { round: 22, home: "水晶宫", away: "Sheffield Utd", homeScore: 3, awayScore: 2 },
            { round: 22, home: "阿斯顿维拉", away: "Newcastle", homeScore: 1, awayScore: 3 },
            { round: 22, home: "Tottenham", away: "布伦特福德", homeScore: 3, awayScore: 2 },
            { round: 22, home: "曼城", away: "伯恩利", homeScore: 3, awayScore: 1 },
            { round: 22, home: "利物浦", away: "切尔西", homeScore: 4, awayScore: 1 },
            { round: 22, home: "West Ham", away: "伯恩茅斯", homeScore: 1, awayScore: 1 },
            { round: 22, home: "Wolves", away: "曼联", homeScore: 3, awayScore: 4 },
            { round: 23, home: "埃弗顿", away: "Tottenham", homeScore: 2, awayScore: 2 },
            { round: 23, home: "Newcastle", away: "Luton", homeScore: 4, awayScore: 4 },
            { round: 23, home: "伯恩利", away: "富勒姆", homeScore: 2, awayScore: 2 },
            { round: 23, home: "Brighton", away: "水晶宫", homeScore: 4, awayScore: 1 },
            { round: 23, home: "Sheffield Utd", away: "阿斯顿维拉", homeScore: 0, awayScore: 5 },
            { round: 23, home: "曼联", away: "West Ham", homeScore: 3, awayScore: 0 },
            { round: 23, home: "伯恩茅斯", away: "诺丁汉森林", homeScore: 1, awayScore: 1 },
            { round: 23, home: "切尔西", away: "Wolves", homeScore: 2, awayScore: 4 },
            { round: 23, home: "阿森纳", away: "利物浦", homeScore: 3, awayScore: 1 },
            { round: 23, home: "布伦特福德", away: "曼城", homeScore: 1, awayScore: 3 },
            { round: 24, home: "曼城", away: "埃弗顿", homeScore: 2, awayScore: 0 },
            { round: 24, home: "富勒姆", away: "伯恩茅斯", homeScore: 3, awayScore: 1 },
            { round: 24, home: "Wolves", away: "布伦特福德", homeScore: 0, awayScore: 2 },
            { round: 24, home: "利物浦", away: "伯恩利", homeScore: 3, awayScore: 1 },
            { round: 24, home: "Tottenham", away: "Brighton", homeScore: 2, awayScore: 1 },
            { round: 24, home: "Luton", away: "Sheffield Utd", homeScore: 1, awayScore: 3 },
            { round: 24, home: "诺丁汉森林", away: "Newcastle", homeScore: 2, awayScore: 3 },
            { round: 24, home: "West Ham", away: "阿森纳", homeScore: 0, awayScore: 6 },
            { round: 24, home: "阿斯顿维拉", away: "曼联", homeScore: 1, awayScore: 2 },
            { round: 24, home: "水晶宫", away: "切尔西", homeScore: 1, awayScore: 3 },
            { round: 25, home: "布伦特福德", away: "利物浦", homeScore: 1, awayScore: 4 },
            { round: 25, home: "Newcastle", away: "伯恩茅斯", homeScore: 2, awayScore: 2 },
            { round: 25, home: "富勒姆", away: "阿斯顿维拉", homeScore: 1, awayScore: 2 },
            { round: 25, home: "伯恩利", away: "阿森纳", homeScore: 0, awayScore: 5 },
            { round: 25, home: "Tottenham", away: "Wolves", homeScore: 1, awayScore: 2 },
            { round: 25, home: "诺丁汉森林", away: "West Ham", homeScore: 2, awayScore: 0 },
            { round: 25, home: "曼城", away: "切尔西", homeScore: 1, awayScore: 1 },
            { round: 25, home: "Sheffield Utd", away: "Brighton", homeScore: 0, awayScore: 5 },
            { round: 25, home: "Luton", away: "曼联", homeScore: 1, awayScore: 2 },
            { round: 25, home: "埃弗顿", away: "水晶宫", homeScore: 1, awayScore: 1 },
            { round: 18, home: "曼城", away: "布伦特福德", homeScore: 1, awayScore: 0 },
            { round: 26, home: "利物浦", away: "Luton", homeScore: 4, awayScore: 1 },
            { round: 26, home: "曼联", away: "富勒姆", homeScore: 1, awayScore: 2 },
            { round: 26, home: "Brighton", away: "埃弗顿", homeScore: 1, awayScore: 1 },
            { round: 26, home: "水晶宫", away: "伯恩利", homeScore: 3, awayScore: 0 },
            { round: 26, home: "阿斯顿维拉", away: "诺丁汉森林", homeScore: 4, awayScore: 2 },
            { round: 26, home: "伯恩茅斯", away: "曼城", homeScore: 0, awayScore: 1 },
            { round: 26, home: "阿森纳", away: "Newcastle", homeScore: 4, awayScore: 1 },
            { round: 26, home: "Wolves", away: "Sheffield Utd", homeScore: 1, awayScore: 0 },
            { round: 26, home: "West Ham", away: "布伦特福德", homeScore: 4, awayScore: 2 },
            { round: 27, home: "Newcastle", away: "Wolves", homeScore: 3, awayScore: 0 },
            { round: 27, home: "富勒姆", away: "Brighton", homeScore: 3, awayScore: 0 },
            { round: 27, home: "埃弗顿", away: "West Ham", homeScore: 1, awayScore: 3 },
            { round: 27, home: "Tottenham", away: "水晶宫", homeScore: 3, awayScore: 1 },
            { round: 27, home: "布伦特福德", away: "切尔西", homeScore: 2, awayScore: 2 },
            { round: 27, home: "诺丁汉森林", away: "利物浦", homeScore: 0, awayScore: 1 },
            { round: 27, home: "Luton", away: "阿斯顿维拉", homeScore: 2, awayScore: 3 },
            { round: 27, home: "伯恩利", away: "伯恩茅斯", homeScore: 0, awayScore: 2 },
            { round: 27, home: "曼城", away: "曼联", homeScore: 3, awayScore: 1 },
            { round: 27, home: "Sheffield Utd", away: "阿森纳", homeScore: 0, awayScore: 6 },
            { round: 28, home: "曼联", away: "埃弗顿", homeScore: 2, awayScore: 0 },
            { round: 28, home: "伯恩茅斯", away: "Sheffield Utd", homeScore: 2, awayScore: 2 },
            { round: 28, home: "Wolves", away: "富勒姆", homeScore: 2, awayScore: 1 },
            { round: 28, home: "水晶宫", away: "Luton", homeScore: 1, awayScore: 1 },
            { round: 28, home: "阿森纳", away: "布伦特福德", homeScore: 2, awayScore: 1 },
            { round: 28, home: "阿斯顿维拉", away: "Tottenham", homeScore: 0, awayScore: 4 },
            { round: 28, home: "West Ham", away: "伯恩利", homeScore: 2, awayScore: 2 },
            { round: 28, home: "Brighton", away: "诺丁汉森林", homeScore: 1, awayScore: 0 },
            { round: 28, home: "利物浦", away: "曼城", homeScore: 1, awayScore: 1 },
            { round: 28, home: "切尔西", away: "Newcastle", homeScore: 3, awayScore: 2 },
            { round: 17, home: "伯恩茅斯", away: "Luton", homeScore: 4, awayScore: 3 },
            { round: 29, home: "伯恩利", away: "布伦特福德", homeScore: 2, awayScore: 1 },
            { round: 29, home: "Luton", away: "诺丁汉森林", homeScore: 1, awayScore: 1 },
            { round: 29, home: "富勒姆", away: "Tottenham", homeScore: 3, awayScore: 0 },
            { round: 29, home: "West Ham", away: "阿斯顿维拉", homeScore: 1, awayScore: 1 },
            { round: 30, home: "Newcastle", away: "West Ham", homeScore: 4, awayScore: 3 },
            { round: 30, home: "伯恩茅斯", away: "埃弗顿", homeScore: 2, awayScore: 1 },
            { round: 30, home: "Tottenham", away: "Luton", homeScore: 2, awayScore: 1 },
            { round: 30, home: "切尔西", away: "伯恩利", homeScore: 2, awayScore: 2 },
            { round: 30, home: "Sheffield Utd", away: "富勒姆", homeScore: 3, awayScore: 3 },
            { round: 30, home: "诺丁汉森林", away: "水晶宫", homeScore: 1, awayScore: 1 },
            { round: 30, home: "阿斯顿维拉", away: "Wolves", homeScore: 2, awayScore: 0 },
            { round: 30, home: "布伦特福德", away: "曼联", homeScore: 1, awayScore: 1 },
            { round: 30, home: "利物浦", away: "Brighton", homeScore: 2, awayScore: 1 },
            { round: 30, home: "曼城", away: "阿森纳", homeScore: 0, awayScore: 0 },
            { round: 31, home: "Newcastle", away: "埃弗顿", homeScore: 1, awayScore: 1 },
            { round: 31, home: "诺丁汉森林", away: "富勒姆", homeScore: 3, awayScore: 1 },
            { round: 31, home: "伯恩茅斯", away: "水晶宫", homeScore: 1, awayScore: 0 },
            { round: 31, home: "伯恩利", away: "Wolves", homeScore: 1, awayScore: 1 },
            { round: 31, home: "West Ham", away: "Tottenham", homeScore: 1, awayScore: 1 },
            { round: 31, home: "阿森纳", away: "Luton", homeScore: 2, awayScore: 0 },
            { round: 31, home: "布伦特福德", away: "Brighton", homeScore: 0, awayScore: 0 },
            { round: 31, home: "曼城", away: "阿斯顿维拉", homeScore: 4, awayScore: 1 },
            { round: 31, home: "利物浦", away: "Sheffield Utd", homeScore: 3, awayScore: 1 },
            { round: 31, home: "切尔西", away: "曼联", homeScore: 4, awayScore: 3 },
            { round: 32, home: "水晶宫", away: "曼城", homeScore: 2, awayScore: 4 },
            { round: 32, home: "富勒姆", away: "Newcastle", homeScore: 0, awayScore: 1 },
            { round: 32, home: "Wolves", away: "West Ham", homeScore: 1, awayScore: 2 },
            { round: 32, home: "埃弗顿", away: "伯恩利", homeScore: 1, awayScore: 0 },
            { round: 32, home: "阿斯顿维拉", away: "布伦特福德", homeScore: 3, awayScore: 3 },
            { round: 32, home: "Luton", away: "伯恩茅斯", homeScore: 2, awayScore: 1 },
            { round: 32, home: "Brighton", away: "阿森纳", homeScore: 0, awayScore: 3 },
            { round: 32, home: "曼联", away: "利物浦", homeScore: 2, awayScore: 2 },
            { round: 32, home: "Sheffield Utd", away: "切尔西", homeScore: 2, awayScore: 2 },
            { round: 32, home: "Tottenham", away: "诺丁汉森林", homeScore: 3, awayScore: 1 },
            { round: 33, home: "Newcastle", away: "Tottenham", homeScore: 4, awayScore: 0 },
            { round: 33, home: "伯恩利", away: "Brighton", homeScore: 1, awayScore: 1 },
            { round: 33, home: "曼城", away: "Luton", homeScore: 5, awayScore: 1 },
            { round: 33, home: "布伦特福德", away: "Sheffield Utd", homeScore: 2, awayScore: 0 },
            { round: 33, home: "诺丁汉森林", away: "Wolves", homeScore: 2, awayScore: 2 },
            { round: 33, home: "伯恩茅斯", away: "曼联", homeScore: 2, awayScore: 2 },
            { round: 33, home: "利物浦", away: "水晶宫", homeScore: 0, awayScore: 1 },
            { round: 33, home: "West Ham", away: "富勒姆", homeScore: 0, awayScore: 2 },
            { round: 33, home: "阿森纳", away: "阿斯顿维拉", homeScore: 0, awayScore: 2 },
            { round: 33, home: "切尔西", away: "埃弗顿", homeScore: 6, awayScore: 0 },
            { round: 34, home: "Sheffield Utd", away: "伯恩利", homeScore: 1, awayScore: 4 },
            { round: 34, home: "Luton", away: "布伦特福德", homeScore: 1, awayScore: 5 },
            { round: 34, home: "Wolves", away: "阿森纳", homeScore: 0, awayScore: 2 },
            { round: 34, home: "埃弗顿", away: "诺丁汉森林", homeScore: 2, awayScore: 0 },
            { round: 34, home: "水晶宫", away: "West Ham", homeScore: 5, awayScore: 2 },
            { round: 34, home: "阿斯顿维拉", away: "伯恩茅斯", homeScore: 3, awayScore: 1 },
            { round: 34, home: "富勒姆", away: "利物浦", homeScore: 1, awayScore: 3 },
            { round: 29, home: "阿森纳", away: "切尔西", homeScore: 5, awayScore: 0 },
            { round: 29, home: "Wolves", away: "伯恩茅斯", homeScore: 0, awayScore: 1 },
            { round: 29, home: "曼联", away: "Sheffield Utd", homeScore: 4, awayScore: 2 },
            { round: 29, home: "埃弗顿", away: "利物浦", homeScore: 2, awayScore: 0 },
            { round: 29, home: "水晶宫", away: "Newcastle", homeScore: 2, awayScore: 0 },
            { round: 29, home: "Brighton", away: "曼城", homeScore: 0, awayScore: 4 },
            { round: 35, home: "West Ham", away: "利物浦", homeScore: 2, awayScore: 2 },
            { round: 35, home: "曼联", away: "伯恩利", homeScore: 1, awayScore: 1 },
            { round: 35, home: "Newcastle", away: "Sheffield Utd", homeScore: 5, awayScore: 1 },
            { round: 35, home: "富勒姆", away: "水晶宫", homeScore: 1, awayScore: 1 },
            { round: 35, home: "Wolves", away: "Luton", homeScore: 2, awayScore: 1 },
            { round: 35, home: "埃弗顿", away: "布伦特福德", homeScore: 1, awayScore: 0 },
            { round: 35, home: "阿斯顿维拉", away: "切尔西", homeScore: 2, awayScore: 2 },
            { round: 35, home: "伯恩茅斯", away: "Brighton", homeScore: 3, awayScore: 0 },
            { round: 35, home: "Tottenham", away: "阿森纳", homeScore: 2, awayScore: 3 },
            { round: 35, home: "诺丁汉森林", away: "曼城", homeScore: 0, awayScore: 2 },
            { round: 26, home: "切尔西", away: "Tottenham", homeScore: 2, awayScore: 0 },
            { round: 36, home: "Luton", away: "埃弗顿", homeScore: 1, awayScore: 1 },
            { round: 36, home: "阿森纳", away: "伯恩茅斯", homeScore: 3, awayScore: 0 },
            { round: 36, home: "伯恩利", away: "Newcastle", homeScore: 1, awayScore: 4 },
            { round: 36, home: "布伦特福德", away: "富勒姆", homeScore: 0, awayScore: 0 },
            { round: 36, home: "Sheffield Utd", away: "诺丁汉森林", homeScore: 1, awayScore: 3 },
            { round: 36, home: "曼城", away: "Wolves", homeScore: 5, awayScore: 1 },
            { round: 36, home: "切尔西", away: "West Ham", homeScore: 5, awayScore: 0 },
            { round: 36, home: "Brighton", away: "阿斯顿维拉", homeScore: 1, awayScore: 0 },
            { round: 36, home: "利物浦", away: "Tottenham", homeScore: 4, awayScore: 2 },
            { round: 36, home: "水晶宫", away: "曼联", homeScore: 4, awayScore: 0 },
            { round: 37, home: "富勒姆", away: "曼城", homeScore: 0, awayScore: 4 },
            { round: 37, home: "Newcastle", away: "Brighton", homeScore: 1, awayScore: 1 },
            { round: 37, home: "伯恩茅斯", away: "布伦特福德", homeScore: 1, awayScore: 2 },
            { round: 37, home: "Wolves", away: "水晶宫", homeScore: 1, awayScore: 3 },
            { round: 37, home: "埃弗顿", away: "Sheffield Utd", homeScore: 1, awayScore: 0 },
            { round: 37, home: "Tottenham", away: "伯恩利", homeScore: 2, awayScore: 1 },
            { round: 37, home: "West Ham", away: "Luton", homeScore: 3, awayScore: 1 },
            { round: 37, home: "诺丁汉森林", away: "切尔西", homeScore: 2, awayScore: 3 },
            { round: 37, home: "曼联", away: "阿森纳", homeScore: 0, awayScore: 1 },
            { round: 37, home: "阿斯顿维拉", away: "利物浦", homeScore: 3, awayScore: 3 },
            { round: 34, home: "Tottenham", away: "曼城", homeScore: 0, awayScore: 2 },
            { round: 34, home: "Brighton", away: "切尔西", homeScore: 1, awayScore: 2 },
            { round: 34, home: "曼联", away: "Newcastle", homeScore: 3, awayScore: 2 },
            { round: 38, home: "利物浦", away: "Wolves", homeScore: 2, awayScore: 0 },
            { round: 38, home: "阿森纳", away: "埃弗顿", homeScore: 2, awayScore: 1 },
            { round: 38, home: "伯恩利", away: "诺丁汉森林", homeScore: 1, awayScore: 2 },
            { round: 38, home: "切尔西", away: "伯恩茅斯", homeScore: 2, awayScore: 1 },
            { round: 38, home: "曼城", away: "West Ham", homeScore: 3, awayScore: 1 },
            { round: 38, home: "Brighton", away: "曼联", homeScore: 0, awayScore: 2 },
            { round: 38, home: "水晶宫", away: "阿斯顿维拉", homeScore: 5, awayScore: 0 },
            { round: 38, home: "布伦特福德", away: "Newcastle", homeScore: 2, awayScore: 4 },
            { round: 38, home: "Sheffield Utd", away: "Tottenham", homeScore: 0, awayScore: 3 },
            { round: 38, home: "Luton", away: "富勒姆", homeScore: 2, awayScore: 4 },
        ],
        "penalties": {"埃弗顿": 8, "诺丁汉森林": 4,}
    }
};